baseURL = 'https://lurchingabomination.space/'
languageCode = 'en-uk'
title = 'Andrew_McKenna'
theme = 'risotto'
author = "Andrew McKenna"
copyright = "© Andrew McKenna. Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"


# Automatically add content sections to main menu
sectionPagesMenu = "main"

[pagination]
pagerSize = 3

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "About Me"
description = "Hi, I'm Andrew, welcome to my portfolio website"
# unicode/emoji logo:
logo = "💻"
# or use an image:
#logo_image = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/pseudonym-git"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:portfoliowebsite.plenty168@aleeas.com"


[menu]

  [[menu.main]]
    identifier = "my_projects"
    name = "my_projects"
    url = "/my_projects/"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true
